BRANCH = "develop"
MASTER_HOST = "ec2-54-254-127-209.ap-southeast-1.compute.amazonaws.com"
PROJECT_CODE_URL = "yuiizzy"
PROJECT_NAME = "yuiizzy"
REPOSITORY_URL = "https://github.com/AttakornP/yuiizzy.git"
